version: "3"
services:
  www:
    build: ./dockerfiles/apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0.16
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d
      - /home/kai/mysql_data:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - default
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /home/kai/timescale_data:/var/lib/postgresql/data
    networks:
      - default
  pgadmin:
    build: ./dockerfiles/pgadmin
    depends_on:
      - timescale
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kai.rauer@gsits.de
      PGADMIN_DEFAULT_PASSWORD: password1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /home/kai/pgadmin_data:/var/lib/pgadmin
      - /home/kai/dockertest2/conf/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - default
